In [ ]:
10/3

3.3333333333333335

In [ ]:
while True:
  pass

KeyboardInterrupt: 

マークダウンセル

In [ ]:
1+1

2

In [ ]:
7**3

343

In [ ]:
2**2**2**2

65536

In [ ]:
import math
(math.sqrt(5)+1)/2


1.618033988749895

In [ ]:
BMI  # 未定義の変数

NameError: name 'BMI' is not defined

In [ ]:
x = 10
x *= 3
print(x)

30


In [ ]:
def bmi(height,weight):
  bmi = weight / (height/100)**2
  return bmi

bmi(172,55)


18.591130340724717

In [ ]:
def ft_to_cm(f,i):
  return 30.48 * f + 30.48 / 12 * i

assert round(ft_to_cm(5, 2) - 157.48, 6) == 0
assert round(ft_to_cm(6, 5) - 195.58, 6) == 0

In [ ]:
def quadratic(a,b,c,x):
  return a* x**2 + b*x + c

assert quadratic(1, 2, 1, 3) == 16
assert quadratic(1, -5, -2, 7) == 12

In [ ]:
import math
def heron(a,b,c):
  s = 0.5 * (a + b + c)
  return math.sqrt(s * (s - a) * (s - b) * (s - c))

s = 100
heron(3,4,5)

s

100

In [ ]:
import math
def heron(a,b,c):
    s = 0.5*(a+b+c)
    print('The value of s is', s)
    return print(math.sqrt(s * (s-a) * (s-b) * (s-c)))

heron(2,2,2)

The value of s is 3.0
1.7320508075688772


In [ ]:
import math
def qe_disc(a,b,c):
   return b**2 - 4*a*c

def qe_solution1(a,b,c):
  return (-b - math.sqrt(qe_disc(a,b,c))) / (2*a)

def qe_solution2(a,b,c):
  return (-b + math.sqrt(qe_disc(a,b,c))) / (2*a)

assert qe_disc(1, -2, 1) == 0
assert qe_disc(1, -5, 6) == 1
assert round(qe_solution1(1, -2, 1) - 1, 6) == 0
assert round(qe_solution2(1, -2, 1) - 1, 6) == 0
assert round(qe_solution1(1, -5, 6) - 2, 6) == 0
assert round(qe_solution2(1, -5, 6) - 3, 6) == 0

In [ ]:
def absolute(x):
  if x < 0:
    return -x
  return x

assert absolute(-2) == 2
assert absolute(0) == 0
assert absolute(5) == 5

In [ ]:
def sign(x):
  if x > 0:
    return 1
  elif x < 0:
    return -1
  return 0

assert sign(5) == 1
assert sign(-5) == -1
assert sign(0) == 0

In [ ]:
print(None)

None


In [ ]:
def fib(n):
  if n == 1:
    return 0
  elif n == 2:
    return 1
  else:
    return fib(n-1) + fib(n-2)

fib(11)


55

In [ ]:
def median(a,b,c):
  if a > b:
    if b > c:
      return b
    elif a > c:
      return c
    return a
  elif c > b:
    return b
  elif c > a:
    return c
  return a

assert median(3, 1, 2) == 2

In [ ]:
def remove_punctuations(str_engsentences):
  ans = str_engsentences.replace('.','')
  ans = ans.replace(',','')
  ans = ans.replace(':','')
  ans = ans.replace(';','')
  ans = ans.replace('!','')
  ans = ans.replace('?','')
  return ans

print(remove_punctuations('Quiet, uh, donations, you want me to make a donation to the coast guard youth auxiliary?') == 'Quiet uh donations you want me to make a donation to the coast guard youth auxiliary')

True


In [ ]:
def atgc_bppair(str_atgc):
  str_pair = str_atgc.replace("A","tmp1")
  str_pair = str_pair.replace("T","A")
  str_pair = str_pair.replace("tmp1","T")
  str_pair = str_pair.replace("G","tmp2")
  str_pair = str_pair.replace("C","G")
  str_pair = str_pair.replace("tmp2","C")
  return str_pair

print(atgc_bppair('AAGCCCCATGGTAA'))
print(atgc_bppair('AAGCCCCATGGTAA') == 'TTCGGGGTACCATT')



TTCGGGGTACCATT
True


In [ ]:
def swap_colon(str1: str):
  colon_place: int = str1.index(":")
  result = str1[(colon_place + 1):] + ":" + str1[0:colon_place]
  return result

print(swap_colon('hello:world'))
print(swap_colon('hello:world') == 'world:hello')

world:hello
True


In [ ]:
def atgc_count(str_atgc: str,str_bpname: str):
  return str_atgc.count(str_bpname)

print(atgc_count('AAGCCCCATGGTAA', 'A') == 5)

True


In [ ]:
def check_lower(str_engsentences):
  return str_engsentences == str_engsentences.lower()

print(check_lower('down down down') == True)
print(check_lower('There were doors all round the hall, but they were all locked') == False)

True
True


In [ ]:
def remove_clause(str_engsentences: str):
  com_index = str_engsentences.index(",")
  str_res = str_engsentences[com_index + 1:]
  str_res =str_res.lstrip()
  return str_res.capitalize()

print(remove_clause("It's being seen, but you aren't observing.") == "But you aren't observing.")

True


In [ ]:
def remove_evenindex(ln):
  return ln[1::2]

print(remove_evenindex(['a', 'b', 'c', 'd', 'e', 'f', 'g']) == ['b', 'd', 'f'] )
print(remove_evenindex([1, 2, 3, 4, 5]) == [2, 4])


True
True


In [ ]:
def change_domain(email: str,domain: str):
  x = list(email)
  domain_index = email.index("@")
  del x[domain_index:]
  y = ''.join(x)
  z = y + "@" + domain
  print(z)
  return z

print(change_domain('spam@utokyo-ipp.org', 'ipp.u-tokyo.ac.jp') == 'spam@ipp.u-tokyo.ac.jp')



spam@ipp.u-tokyo.ac.jp
True


In [ ]:
def change_domain(email: str,domain: str):
  return "@".join([email.split("@")[0],domain])



In [ ]:
def reverse_totuple(ln):
  ln.reverse()
  return tuple(ln)

print(reverse_totuple([1, 2, 3, 4, 5]) == (5, 4, 3, 2, 1))

True


In [ ]:
def sum_list(ln: list):
  sum: int = 0
  for x in ln:
    sum += x
  return sum

print(sum_list([10, 20, 30]) == 60)
print(sum_list([-1, 2, -3, 4, -5]) == -3)


True
True


In [ ]:
def atgc_countlist(str_atgc):
    list_count = []
    for i in "ATGC":
        bp_cnt = str_atgc.count(i)
        list_count.append([bp_cnt,i])
    return list_count

print(sorted(atgc_countlist('AAGCCCCATGGTAA')) == sorted([[5, 'A'], [2, 'T'], [3, 'G'], [4, 'C']]))


True


In [ ]:
def exception3(x,y,z):
    if x == y:
        return z
    elif x == z:
        return y
    return x

print(exception3(1,2,2))
print(exception3(4,2,4))
print(exception3(9,3,9))

1
2
3


In [ ]:
def exception9(a):
    a1 = a[:3]
    a2 = a[3:6]
    a3 = a[6:]
    if a1 == a2:
        return exception3(a[6],a[7],a[8])
    elif a2 == a3:
        return exception3(a[0],a[1],a[2])
    return exception3(a[3],a[4],a[5])

print(exception9([1,2,2,2,2,2,2,2,2]))
print(exception9([4,4,4,4,4,2,4,4,4]))
print(exception9([9,9,9,9,9,9,9,9,3]))


1
2
3


In [ ]:
x = 0  # example: 3, 0, -4

if x > 0:
    print('x is greater than zero.')
elif x < 0:
    print('x is less than zero, but x will be 0')
    x = 0
else:
    print('x is zero.')

print(x)

x is zero.
0


In [ ]:
x = -1
if 2 <= x < 3:
    print('x is larger than or equal to 2, and less than 3')
elif 1 <= x < 2:
    print('x is larger than or equal to 1, and less than 2')
elif x < 1:
    print('x is less than 1')
else:
    print('x is larger or equal to 3')

x is less than 1


In [ ]:
x = -4       # del x のエラーを抑制するため
y = 10

del x           # x を未定義に

if x > 5 or y > 5:
    print("'x' or 'y' is larger than 5")

NameError: name 'x' is not defined

In [ ]:
x = 10
y = 10          # del y のエラーを抑制するため

del y           # y を未定義に

if x > 5 or y > 5:
    print("'x' or 'y' is larger than 5")

'x' or 'y' is larger than 5


In [ ]:
def reverse_lookup(list1):
    dict1 = {}
    for value in list1:
        dict1[value] = list1.index(value)
    return dict1

print(reverse_lookup(['apple', 'pen', 'orange']))
print(reverse_lookup(['apple', 'pen', 'orange']) == {'apple': 0, 'orange': 2, 'pen': 1})

{'apple': 0, 'pen': 1, 'orange': 2}
True


In [ ]:
def handle_collision(dict1,str1):
    x = len(str1)

    if dict1.get(x):
        dict1[x].append(str1)
    else:
        ls = [str1]
        dict1.setdefault(x,ls)



dic1_orig = {3: ['ham', 'egg'], 6: ['coffee', 'brandy'], 9: ['port wine'], 15: ['curried chicken']}
dic1_result = {3: ['ham', 'egg', 'tea'], 6: ['coffee', 'brandy'], 9: ['port wine'], 15: ['curried chicken']}
handle_collision(dic1_orig, 'tea')
print(dic1_orig == dic1_result)

True


In [ ]:
print(chr(111155))

𛈳


In [ ]:
def reverse_lookup2(dic1):
    dic2 = {}
    for key,value in dic1.items():
        dic2[value] = key
    return dic2
print(reverse_lookup2({'apple': 3, 'pen': 5, 'orange': 7}) == {3: 'apple', 5: 'pen', 7: 'orange'})



True


In [ ]:
def sum_n(x: int,y:int):
    sum: int = 0
    for i in range(x,(y + 1)):
        sum += i
    return sum

print(sum_n(1, 3) == 6)

True


In [ ]:
def construct_list(int_size):
    ln = []
    for i in range(int_size):
        ln.append(i)
    return ln

print(construct_list(10) == [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

True


In [ ]:
def sum_lists(list1):
    value_sum: int = 0 #リストの各要素の和
    total_sum: int = 0 #リストの総和
    for i in range(len(list1)):
        for j in range(len(list1[i])):
            value_sum += list1[i][j]
    return value_sum

print(sum_lists([[20, 5], [6, 16, 14, 5], [16, 8, 16, 17, 14], [1], [5, 3, 5, 7]]) == 158)

True


In [ ]:
def sum_lists(list1):
    total = 0
    for list2 in list1:  # for j in range(len(list1)):とlist2 = list1[j]としてもよい
        #print(list2)
        for i in range(len(list2)):
            #print(i, list2[i])
            total += list2[i]
    return total

print(sum_lists([[20, 5], [6, 16, 14, 5], [16, 8, 16, 17, 14], [1], [5, 3, 5, 7]]) == 158)

True


In [ ]:
def sum_matrix(list1,list2):
    list3 = [[0,0,0],[0,0,0],[0,0,0]]
    for i in range(3):
        for j in range(3):
            list3[i][j] = list1[i][j] + list2[i][j]
    return list3

print(sum_matrix([[1,2,3],[4,5,6],[7,8,9]], [[1,4,7],[2,5,8],[3,6,9]]) == [[2, 6, 10], [6, 10, 14], [10, 14, 18]])

True


In [ ]:
def simple_match(str1: str,str2: str):
    for i,val in enumerate(str1):
        if val == str2[0]:
            j: int = 0 #str2を管理する変数
            while j < len(str2) and i + j < len(str1) and str1[i + j] == str2[j]:
                j += 1
            if j == len(str2):
                return i
    return -1
print(simple_match('location', 'cat') == 2)
print(simple_match('soccer', 'cat') == -1)
print(simple_match('category', 'cate') == 0)
print(simple_match('carpetcat', 'cat') == 6)

True
True
True
True


In [ ]:
from time import sleep
i = 1
while i <= 10:
    print('Yeah!')
    sleep(1)
    i += 1

Yeah!
Yeah!
Yeah!
Yeah!
Yeah!
Yeah!
Yeah!
Yeah!
Yeah!
Yeah!


In [ ]:
def collect_engwords(str_engsentence: str):
    word: str = ""
    word_list: list =[]

    for ch in ["," , ".", "?", "!", ";", ":"]:
        str_engsentence = str_engsentence.replace(ch, " ") # , . ! ? をスペースに変換

    for i in str_engsentence:
        if i != " ":
            word += i
        else:
            if len(word) <= 2:
                word = ""
            else:
                word_list.append(word)
                word = ""
    return word_list

print(collect_engwords('Unfortunately no, it requires something with a little more kick, plutonium.'))
print(collect_engwords('Unfortunately no, it requires something with a little more kick, plutonium.') == ['Unfortunately', 'requires',
'something', 'with', 'little', 'more', 'kick', 'plutonium'])

['Unfortunately', 'requires', 'something', 'with', 'little', 'more', 'kick', 'plutonium']
True


In [ ]:
def swap_lists(ln1,ln2):
    tmp_list = ln1[:]

    for i in range(1,len(ln1),2):
        ln1[i] = ln2[i]
    for i in range(1,len(ln2),2):
        ln2[i] = tmp_list[i]
    ln1_tuple = tuple(ln1)
    ln2_tuple = tuple(ln2)
    return(ln1_tuple,ln2_tuple)

print(swap_lists([1, 2, 3, 4, 5], ['a', 'b', 'c', 'd', 'e']))
print(swap_lists([1, 2, 3, 4, 5], ['a', 'b', 'c', 'd', 'e']) == ([1, 'b', 3, 'd', 5], ['a', 2, 'c', 4, 'e']))

((1, 'b', 3, 'd', 5), ('a', 2, 'c', 4, 'e'))
False


In [ ]:
def count_capitalletters(str1):
    remove_chars = [" ", "!", "?", ",", ".", ";", ":"]
    str1_letters = "".join(ch for ch in str1 if ch not in remove_chars) #str1から記号とスペースを取り除く。
    str1_letters_upper = str1_letters.upper()
    cnt = 0

    for i in range(len(str1_letters)):
        if str1_letters[i] == str1_letters_upper[i]:
            cnt += 1
    return cnt

print(count_capitalletters('Que Será, Será') == 3)

True


In [ ]:
def identify_codons(str_augc):
    val: str = "" #文字列を格納する変数
    result: list = []
    data = "".join([str_augc,"#"])
    for i in data:
        val += i
        if len(val) == 3 and i != "#":
            result.append(val)
            val = ""
        elif (i == "#") and (len(val)) > 1:
            rem_val = val.replace("#","")
            result.append(rem_val)
    return result

print(identify_codons('14980'))

80
['149', '80']


In [ ]:
def add_commas(int1): #失敗作
    intTOstr = str(int1)
    x = len(intTOstr)
    y = len(intTOstr)//3
    sep_val = []
    for i in range(y):
        if x % 3 == 0:
            sep_val.append(intTOstr[i*3: i*3+3])
        elif x % 3 == 1:
            sep_val.append(intTOstr[0])
            sep_val.append(intTOstr[i*3 +1: i*3 +4])
        else:
            sep_val.append(intTOstr[0:2])
            sep_val.append(intTOstr[i*3 +2: i*3 +5])
    result = ",".join(sep_val)
    return result

print(add_commas(14980) == '14,980')
print(add_commas(3980) == '3,980')
print(add_commas(298) == '298')
print(add_commas(1000000) == '1,000,000')
print(add_commas(1000000))

True
True
True
False
1,000,1,000


In [ ]:
def add_commas(int1):
    str1 = str(int1)
    sp_nums = [] #3桁に区切った文字列を格納するリスト
    while str1:
        sp_nums.append(str1[-3:])
        str1 = str1[:-3]
    return ",".join(reversed(sp_nums))

print(add_commas(14980))
print(add_commas(3980))
print(add_commas(298))
print(add_commas(1000000))

print(add_commas(14980) == '14,980')
print(add_commas(3980) == '3,980')
print(add_commas(298) == '298')
print(add_commas(1000000) == '1,000,000')


14,980
3,980
298
1,000,000
True
True
True
True


In [ ]:
def sum_strings(list1: list) -> str:
    k = len(list1)
    str_list = [str(n) for n in list1]  # 変換処理
    if k == 0:
        return ""
    elif k == 1:
        return str_list[0]
    elif k == 2:
        return str_list[0] + " and " + str_list[1]
    return ", ".join(str_list[:-1]) + " and " + str_list[-1]

print(sum_strings(['a', 'b', 'c', 'd']))
print(sum_strings(['a']))
print(sum_strings([1, 2, 3]))

print(sum_strings(['a', 'b', 'c', 'd']) == 'a, b, c and d')
print(sum_strings(['a']) == 'a')
print(sum_strings([1, 2, 3]) == '1, 2 and 3')

a, b, c and d
a
1, 2 and 3
True
True
True


In [ ]:
def handle_collision2(dict1, str1):
    n = len(str1)
    i = n + 1
    j = 1

    if str1 == "":
        return "Error No Value"
    elif n > 10:
        return "Value too long" # 引数が""または10より大きい場合の処理

    dict1.setdefault(n, str1) # nがキー登録されている場合の処理

    if dict1.get(n) != str1:
        while i <= 10:
            if dict1.get(i) is None:
                dict1[i] = str1
                break
            i += 1
        if i == 11:
            while j <= n - 1:
                if dict1.get(j) is None:
                   dict1[j] = str1
                   break
                j += 1


dic1_orig = {6: 'Styles', 4: 'Link', 7: 'Ackroyd'}
handle_collision2(dic1_orig, 'Big Four')
print(dic1_orig == {6: 'Styles', 4: 'Link', 7: 'Ackroyd', 8: 'Big Four'})
dic1_orig = {6: 'Styles', 4: 'Link', 7: 'Ackroyd', 8: 'Big Four', 10: 'Blue Train', 9: 'End House'}
handle_collision2(dic1_orig, 'Edgware')
print(dic1_orig == {6: 'Styles', 4: 'Link', 7: 'Ackroyd', 8: 'Big Four', 10: 'Blue Train', 9: 'End House', 1: 'Edgware'})
dic1_orig = {6: 'Styles', 4: 'Link', 7: 'Ackroyd', 8: 'Big Four', 10: 'Blue Train', 9: 'End House', 1: 'Edgware', 2: 'Orient', 3: 'Three Act', 5: 'Clouds'}
handle_collision2(dic1_orig, 'ABC')
print(dic1_orig == {6: 'Styles', 4: 'Link', 7: 'Ackroyd', 8: 'Big Four', 10: 'Blue Train', 9: 'End House', 1: 'Edgware', 2: 'Orient', 3: 'Three Act', 5: 'Clouds'})


True
True
True


In [ ]:
def handle_collision3(list1):
    dict1 = {}
    for list2 in list1:
        if list2[0] not in dict1.keys():
            dict1[list2[0]] = list2[1]
    return dict1

print(handle_collision3([[3, 'Richard III'], [1, 'Othello'], [2, 'Tempest'], [3, 'King John'], [4, 'Midsummer'], [1, 'Lear']]) == {1: 'Othello', 2: 'Tempest', 3: 'Richard III', 4: 'Midsummer'})

True


In [ ]:
def last_line(name):
    f = open(name, "r")
    l_line = "" #最終行を格納する変数
    while True:
        new_line = f.readline()
            if new_line == "":
                f.close()
                return l_line
            l_line = new_line


In [ ]:
def number_of_characters(name):
    f = open(name, "r")
    all_line = f.read()
    f.close()
    return len(all_line)

In [ ]:
def file_upper(infile, outfile):
    with open(infile, "r") as in:
        in_upper = in.read().upper()
    with open(outfile, "w") as out:
        out.write(in_upper)

In [ ]:
def last_line(name):
    with open(name, "r") as f:
        for line in f:
            pass
        return line

In [ ]:
def but_first(ls):
    it = iter(ls)
    next(it)
    return it

it = but_first([0,2,4,6,8])
print(type(it))
assert type(it) == type(iter([])) # type(it) では it は消費されない
assert list(it) == [2,4,6,8]

<class 'list_iterator'>


In [ ]:
from math import sqrt, sin, pi
print(sqrt(2))
print(sin(pi))

1.4142135623730951
1.2246467991473532e-16


In [ ]:
def arange_square_matrix(n):
    import numpy as np
    ls =[]
    for i in range(n):
        ls.append(np.arange(i, (i + n)))
    return np.array(ls)

print(arange_square_matrix(3))
print(all(map(all,(arange_square_matrix(3) == np.array([[0,1,2],[1,2,3],[2,3,4]])))))

[[0 1 2]
 [1 2 3]
 [2 3 4]]
True


In [ ]:
def arange_square_matrix(n):
    import numpy as np
    return np.array([np.arange(i, i + n) for i in range(3)])

print(arange_square_matrix(3))
print(all(map(all,(arange_square_matrix(3) == np.array([[0,1,2],[1,2,3],[2,3,4]])))))


[[0 1 2]
 [1 2 3]
 [2 3 4]]
True


In [ ]:
str1 = "123, 45, -3"
[int(x) for x in str1.split(",")]

[123, 45, -3]

In [ ]:
def var(lst):
    lst_mean = sum(lst) / len(lst)
    return sum([(x - lst_mean) ** 2 for x in lst]) / len(lst)

print(var([3,4,1,2]) == 1.25)

True


In [ ]:
def sum_lists(list1):
    return sum([sum(x) for x in list1])

print(sum_lists([[20, 5], [6, 16, 14, 5], [16, 8, 16, 17, 14], [1], [5, 3, 5, 7]]) == 158)

True


In [ ]:
def sum_matrix(list1, list2):
    list3 = [[(list1[i][j] + list2[i][j]) for j in range(3)] for i in range(3)]
    return list3

print(sum_matrix([[1,5,3],[4,5,6],[7,8,9]], [[1,4,7],[2,5,8],[3,6,9]]))

[[2, 9, 10], [6, 10, 14], [10, 14, 18]]


In [ ]:
def sum_matrix(list1, list2):
    list3 = [(list1[i][j] + list2[i][j]) for i in range(3) for j in range(3)]
    return list3

print(sum_matrix([[1,5,3],[4,5,6],[7,8,9]], [[1,4,7],[2,5,8],[3,6,9]]))

[2, 9, 10, 6, 10, 14, 10, 14, 18]


In [ ]:
def max_value_key(d):
    return max(d, key= lambda k: d[k])

print(max_value_key({3:10, 5:2, 9:1}) == 3)

True


In [ ]:
def max_abs(ln):
    return max(map(abs, ln))

print(max_abs([3,-8,1,0,7,-5]) == 8)

True


In [ ]:
def number_of_big_numbers(ln, n):
    return len(list(filter(lambda x: x > n, ln)))

print(number_of_big_numbers([10, 0, 7, 1, 5, 2, 9], 5) == 3)

True


In [ ]:
def number_of_long_lines(file, n):
    with open(file, "r") as f:
        return sum(map(lambda x: 1, flter(lambda x: len(x) > n, f)))

In [ ]:
class StringFileIterator(HelloFileIterator):
    def __init__(self, s, n):
        self.s = s: str  #文字列
        self.n = n: int  #繰り返し回数
    def readline(self):
        if self.n == 0:
            return ""
        self.n = self.n - 1
        return self.s

In [ ]:
def check_characters(str1):
    result = {x for x in str1}
    return len(result)

print(check_characters('Onde a terra acaba e o mar começa') == 13)

True


In [ ]:
def check_dicsize(dic1):
    dic_keys = dic1.keys()
    return len(dic_keys)

print(check_dicsize({'apple': 0, 'orange': 2, 'pen': 1}) == 3)


True


In [ ]:
def count_words2(str_engsentences):
    import re
    words = re.sub(r"[?!,\.]", "",str_engsentences)
    set1 = set(words.split())
    return len(set1)

print(count_words2('From Stettin in the Baltic to Trieste in the Adriatic an iron curtain has descended across the Continent.') == 15)

True


In [ ]:
import re
def check_monthstr(str1):
    return re.search("0(1|2|3|4|5|6|7|8|9)|1(0|1|2)", str1)

print(check_monthstr('10').group() == '10') # group()については後半に説明があります（オプショナル）
print(check_monthstr('mon1521vb') == None)
print(check_monthstr('00an23') == None)
print(check_monthstr('13302').group() == '02')

True
True
True
True


In [ ]:
import re
def check_timestr(str1):
    reg_hour = "(0(0|1|2|3|4|5|6|7|8|9)|10|11)"
    reg_minute = "((0|1|2|3|4|5)(0|1|2|3|4|5|6|7|8|9))"
    return re.search(reg_hour + ":" + reg_minute, str1)

print(check_timestr('10:23').group() == '10:23') # group()については後半に説明があります（オプショナル）
print(check_timestr('time?1023') == None)
print(check_timestr('time?11:23').group() == '11:23')
print(check_timestr('12:3xx1;23ah23:23') == None)

True
True
True
True


In [ ]:
import re
def check_ipv4str(str1):
    reg_ip = "((0|1|2)(0|1|2|3|4|5)(0|1|2|3|4|5))"
    ipv4 = reg_ip + (":" + reg_ip) * 3
    return re.search(ipv4, str1)

print(check_ipv4str('IP=255:255:255:255').group() == '255:255:255:255')
print(check_ipv4str('notIP=2x5:a5b:2c:255:14:444') == None)
print(check_ipv4str('IP?=25:25:55:155') == None)
print(check_ipv4str('IP?=255:255:255') == None)


True
True
True
True


In [ ]:
import re
def check_monthdaystr(str1):
    reg_m1 = "(01|03|05|07|08|10|12)"
    reg_m2 = "(04|06|09|11)"
    reg_m3 = "02"
    reg_d1 = "((0|1|2)(1|2|3|4|5|6|7|8|9)|10|20|30|31)"
    reg_d2 = "((0|1|2)(1|2|3|4|5|6|7|8|9)|10|20|30)"
    reg_d3 = "((0|1|2)(1|2|3|4|5|6|7|8|9)|10|20)"
    reg_md1 = reg_m1 + "/" + reg_d1
    reg_md2 = reg_m2 + "/" + reg_d2
    reg_md3 = reg_m3 + "/" + reg_d3
    reg_md = f"({reg_md1}|{reg_md2}|{reg_md3})"
    return re.search(reg_md, str1)

print(check_monthdaystr('year11/31month11/30day15hour/27minute/sec').group() == '11/30')
print(check_monthdaystr('11/31') == None)
print(check_monthdaystr('x02f/2d5ax') == None)
print(check_monthdaystr('03/24').group() == '03/24')

True
True
True
True


- 変数をまとめるときはfを使う。
 reg_md = reg_md1|reg_md2|reg_md3 ←NG

In [ ]:
import re
def get_engsentences():
    with open("text-sample.txt", "r") as f:
        lines = f.read()
        word_list = re.split(r"[ ,.?!]*", lines)
    return word_list.sort()

- r"[ ,.?!]*" →r"[,.?!]\s*"に訂正
- sort()は破壊的でNoneを返すから  
word_list.sort()  
return word_list  
が正しい。

In [ ]:
import re
def sumnumbers(words):
    list1 = re.findall(r"\d+\.\d+|\d+", words)
    list2 = map(int,(map(float, list1)))
    return sum(list2)

print(sumnumbers(' 2  33 45, 67.9'))
print(sumnumbers(' 2  33 45, 67.9') == 156)

147
False


- r"_d+|\d+\.\d+"だと67が見つかった時点で探索をやめるので67.9が小数として認識されない。マッチは文字列の左から、正規表現内でも左から探索。

In [ ]:
import re
def check_ACGTstr(str1):
    if str1 == "":
        return False
    not_acgt = re.search("[^ACGT]", str1, re.I)
    if not_acgt:
        return False
    return True

print(check_ACGTstr('AcCGTAGCacATcGgAaaTtGCacT') == True)
print(check_ACGTstr(':ACaacgta24FgtGH') == False)
print(check_ACGTstr('') == False)

True
True
True


- 文字クラスは""で囲う。

In [ ]:
import re
def check_postalcode(str1):
    if re.fullmatch(r"\d\d\d-\d\d\d\d", str1):
        return True
    return False

print(check_postalcode('113-8654') == True)
print(check_postalcode('119-110') == False)
print(check_postalcode('abc-defg') == False)
print(check_postalcode('〒153-0041') == False)
print(check_postalcode('113-86547') == False)

True
True
True
True
True


- str1と\dは==で比較できない。\dという文字列そのものとして比較される。

In [ ]:
import re
def check_extension(str1):
    if re.fullmatch(r"2\d{4,4}", str1):
        return True
    return False

print(check_extension('24115') == True)
print(check_extension('46858') == False)
print(check_extension('☎46666') == False)
print(check_extension('467890') == False)

True
True
True
True


In [ ]:
import re
def get_pos():
    words = {}
    with open("B1S.xmal", "r") as f:
        line = f.readline()
    while line:
        k = re.search(r"pos=\"\w{4,4}", line)
        k.replace('pos="',"")
        v = re.search(r"\>\w+", line)
        v.replace(">","")
        words[k] = v
    return words

- openの引数にに encorfding = "utf-8" を入れておく。

In [ ]:
import re
def get_pos():
    d = {}
    with open("B1S.xml", "r", encording = "utf-8") as f:
        for line in f:
            if "<w " not in line:
                continue
            m_pos = re.search(r'pos="([^"]+)"', line)
            m_word = re.search(r'>([^<]+)</w>', line)
            if m_pos and m_word:
                d[m_word.group(1)] = m_pos.group(1)
    return d